// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthTokens              string
	AuthenticationProviders string
	PasswordResets          string
	Profiles                string
	Roles                   string
	UserRoles               string
	Users                   string
}{
	AuthTokens:              "auth_tokens",
	AuthenticationProviders: "authentication_providers",
	PasswordResets:          "password_resets",
	Profiles:                "profiles",
	Roles:                   "roles",
	UserRoles:               "user_roles",
	Users:                   "users",
}
