// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// PasswordReset is an object representing the database table.
type PasswordReset struct {
	ID                       int         `gqlgen:"id" boil:"id" json:"id" toml:"id" yaml:"id"`
	AuthenticationProviderID int         `gqlgen:"authentication_provider_id" boil:"authentication_provider_id" json:"authentication_provider_id" toml:"authentication_provider_id" yaml:"authentication_provider_id"`
	PasswordResetToken       null.String `gqlgen:"password_reset_token" boil:"password_reset_token" json:"password_reset_token,omitempty" toml:"password_reset_token" yaml:"password_reset_token,omitempty"`
	Status                   null.String `gqlgen:"status" boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	ExpiresAt                null.Time   `gqlgen:"expires_at" boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`
	CreatedAt                null.Time   `gqlgen:"created_at" boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt                null.Time   `gqlgen:"updated_at" boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *passwordResetR `gqlgen:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L passwordResetL  `gqlgen:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PasswordResetColumns = struct {
	ID                       string
	AuthenticationProviderID string
	PasswordResetToken       string
	Status                   string
	ExpiresAt                string
	CreatedAt                string
	UpdatedAt                string
}{
	ID:                       "id",
	AuthenticationProviderID: "authentication_provider_id",
	PasswordResetToken:       "password_reset_token",
	Status:                   "status",
	ExpiresAt:                "expires_at",
	CreatedAt:                "created_at",
	UpdatedAt:                "updated_at",
}

// Generated where

var PasswordResetWhere = struct {
	ID                       whereHelperint
	AuthenticationProviderID whereHelperint
	PasswordResetToken       whereHelpernull_String
	Status                   whereHelpernull_String
	ExpiresAt                whereHelpernull_Time
	CreatedAt                whereHelpernull_Time
	UpdatedAt                whereHelpernull_Time
}{
	ID:                       whereHelperint{field: `id`},
	AuthenticationProviderID: whereHelperint{field: `authentication_provider_id`},
	PasswordResetToken:       whereHelpernull_String{field: `password_reset_token`},
	Status:                   whereHelpernull_String{field: `status`},
	ExpiresAt:                whereHelpernull_Time{field: `expires_at`},
	CreatedAt:                whereHelpernull_Time{field: `created_at`},
	UpdatedAt:                whereHelpernull_Time{field: `updated_at`},
}

// PasswordResetRels is where relationship names are stored.
var PasswordResetRels = struct {
	AuthenticationProvider string
}{
	AuthenticationProvider: "AuthenticationProvider",
}

// passwordResetR is where relationships are stored.
type passwordResetR struct {
	AuthenticationProvider *AuthenticationProvider
}

// NewStruct creates a new relationship struct
func (*passwordResetR) NewStruct() *passwordResetR {
	return &passwordResetR{}
}

// passwordResetL is where Load methods for each relationship are stored.
type passwordResetL struct{}

var (
	passwordResetColumns               = []string{"id", "authentication_provider_id", "password_reset_token", "status", "expires_at", "created_at", "updated_at"}
	passwordResetColumnsWithoutDefault = []string{"authentication_provider_id", "password_reset_token", "status", "expires_at", "created_at", "updated_at"}
	passwordResetColumnsWithDefault    = []string{"id"}
	passwordResetPrimaryKeyColumns     = []string{"id"}
)

type (
	// PasswordResetSlice is an alias for a slice of pointers to PasswordReset.
	// This should generally be used opposed to []PasswordReset.
	PasswordResetSlice []*PasswordReset
	// PasswordResetHook is the signature for custom PasswordReset hook methods
	PasswordResetHook func(context.Context, boil.ContextExecutor, *PasswordReset) error

	passwordResetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	passwordResetType                 = reflect.TypeOf(&PasswordReset{})
	passwordResetMapping              = queries.MakeStructMapping(passwordResetType)
	passwordResetPrimaryKeyMapping, _ = queries.BindMapping(passwordResetType, passwordResetMapping, passwordResetPrimaryKeyColumns)
	passwordResetInsertCacheMut       sync.RWMutex
	passwordResetInsertCache          = make(map[string]insertCache)
	passwordResetUpdateCacheMut       sync.RWMutex
	passwordResetUpdateCache          = make(map[string]updateCache)
	passwordResetUpsertCacheMut       sync.RWMutex
	passwordResetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var passwordResetBeforeInsertHooks []PasswordResetHook
var passwordResetBeforeUpdateHooks []PasswordResetHook
var passwordResetBeforeDeleteHooks []PasswordResetHook
var passwordResetBeforeUpsertHooks []PasswordResetHook

var passwordResetAfterInsertHooks []PasswordResetHook
var passwordResetAfterSelectHooks []PasswordResetHook
var passwordResetAfterUpdateHooks []PasswordResetHook
var passwordResetAfterDeleteHooks []PasswordResetHook
var passwordResetAfterUpsertHooks []PasswordResetHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PasswordReset) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PasswordReset) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PasswordReset) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PasswordReset) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PasswordReset) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PasswordReset) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PasswordReset) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PasswordReset) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PasswordReset) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range passwordResetAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPasswordResetHook registers your hook function for all future operations.
func AddPasswordResetHook(hookPoint boil.HookPoint, passwordResetHook PasswordResetHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		passwordResetBeforeInsertHooks = append(passwordResetBeforeInsertHooks, passwordResetHook)
	case boil.BeforeUpdateHook:
		passwordResetBeforeUpdateHooks = append(passwordResetBeforeUpdateHooks, passwordResetHook)
	case boil.BeforeDeleteHook:
		passwordResetBeforeDeleteHooks = append(passwordResetBeforeDeleteHooks, passwordResetHook)
	case boil.BeforeUpsertHook:
		passwordResetBeforeUpsertHooks = append(passwordResetBeforeUpsertHooks, passwordResetHook)
	case boil.AfterInsertHook:
		passwordResetAfterInsertHooks = append(passwordResetAfterInsertHooks, passwordResetHook)
	case boil.AfterSelectHook:
		passwordResetAfterSelectHooks = append(passwordResetAfterSelectHooks, passwordResetHook)
	case boil.AfterUpdateHook:
		passwordResetAfterUpdateHooks = append(passwordResetAfterUpdateHooks, passwordResetHook)
	case boil.AfterDeleteHook:
		passwordResetAfterDeleteHooks = append(passwordResetAfterDeleteHooks, passwordResetHook)
	case boil.AfterUpsertHook:
		passwordResetAfterUpsertHooks = append(passwordResetAfterUpsertHooks, passwordResetHook)
	}
}

// One returns a single passwordReset record from the query.
func (q passwordResetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PasswordReset, error) {
	o := &PasswordReset{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for password_resets")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PasswordReset records from the query.
func (q passwordResetQuery) All(ctx context.Context, exec boil.ContextExecutor) (PasswordResetSlice, error) {
	var o []*PasswordReset

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PasswordReset slice")
	}

	if len(passwordResetAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PasswordReset records in the query.
func (q passwordResetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count password_resets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q passwordResetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if password_resets exists")
	}

	return count > 0, nil
}

// AuthenticationProvider pointed to by the foreign key.
func (o *PasswordReset) AuthenticationProvider(mods ...qm.QueryMod) authenticationProviderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.AuthenticationProviderID),
	}

	queryMods = append(queryMods, mods...)

	query := AuthenticationProviders(queryMods...)
	queries.SetFrom(query.Query, "`authentication_providers`")

	return query
}

// LoadAuthenticationProvider allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (passwordResetL) LoadAuthenticationProvider(ctx context.Context, e boil.ContextExecutor, singular bool, maybePasswordReset interface{}, mods queries.Applicator) error {
	var slice []*PasswordReset
	var object *PasswordReset

	if singular {
		object = maybePasswordReset.(*PasswordReset)
	} else {
		slice = *maybePasswordReset.(*[]*PasswordReset)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &passwordResetR{}
		}
		args = append(args, object.AuthenticationProviderID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &passwordResetR{}
			}

			for _, a := range args {
				if a == obj.AuthenticationProviderID {
					continue Outer
				}
			}

			args = append(args, obj.AuthenticationProviderID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`authentication_providers`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AuthenticationProvider")
	}

	var resultSlice []*AuthenticationProvider
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AuthenticationProvider")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for authentication_providers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for authentication_providers")
	}

	if len(passwordResetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.AuthenticationProvider = foreign
		if foreign.R == nil {
			foreign.R = &authenticationProviderR{}
		}
		foreign.R.PasswordResets = append(foreign.R.PasswordResets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AuthenticationProviderID == foreign.ID {
				local.R.AuthenticationProvider = foreign
				if foreign.R == nil {
					foreign.R = &authenticationProviderR{}
				}
				foreign.R.PasswordResets = append(foreign.R.PasswordResets, local)
				break
			}
		}
	}

	return nil
}

// SetAuthenticationProvider of the passwordReset to the related item.
// Sets o.R.AuthenticationProvider to related.
// Adds o to related.R.PasswordResets.
func (o *PasswordReset) SetAuthenticationProvider(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AuthenticationProvider) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `password_resets` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"authentication_provider_id"}),
		strmangle.WhereClause("`", "`", 0, passwordResetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AuthenticationProviderID = related.ID
	if o.R == nil {
		o.R = &passwordResetR{
			AuthenticationProvider: related,
		}
	} else {
		o.R.AuthenticationProvider = related
	}

	if related.R == nil {
		related.R = &authenticationProviderR{
			PasswordResets: PasswordResetSlice{o},
		}
	} else {
		related.R.PasswordResets = append(related.R.PasswordResets, o)
	}

	return nil
}

// PasswordResets retrieves all the records using an executor.
func PasswordResets(mods ...qm.QueryMod) passwordResetQuery {
	mods = append(mods, qm.From("`password_resets`"))
	return passwordResetQuery{NewQuery(mods...)}
}

// FindPasswordReset retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPasswordReset(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PasswordReset, error) {
	passwordResetObj := &PasswordReset{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `password_resets` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, passwordResetObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from password_resets")
	}

	return passwordResetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PasswordReset) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no password_resets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(passwordResetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	passwordResetInsertCacheMut.RLock()
	cache, cached := passwordResetInsertCache[key]
	passwordResetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			passwordResetColumns,
			passwordResetColumnsWithDefault,
			passwordResetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(passwordResetType, passwordResetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(passwordResetType, passwordResetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `password_resets` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `password_resets` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `password_resets` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, passwordResetPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into password_resets")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == passwordResetMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for password_resets")
	}

CacheNoHooks:
	if !cached {
		passwordResetInsertCacheMut.Lock()
		passwordResetInsertCache[key] = cache
		passwordResetInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PasswordReset.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PasswordReset) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	passwordResetUpdateCacheMut.RLock()
	cache, cached := passwordResetUpdateCache[key]
	passwordResetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			passwordResetColumns,
			passwordResetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update password_resets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `password_resets` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, passwordResetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(passwordResetType, passwordResetMapping, append(wl, passwordResetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update password_resets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for password_resets")
	}

	if !cached {
		passwordResetUpdateCacheMut.Lock()
		passwordResetUpdateCache[key] = cache
		passwordResetUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q passwordResetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for password_resets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for password_resets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PasswordResetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordResetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `password_resets` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, passwordResetPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in passwordReset slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all passwordReset")
	}
	return rowsAff, nil
}

var mySQLPasswordResetUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PasswordReset) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no password_resets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(passwordResetColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPasswordResetUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	passwordResetUpsertCacheMut.RLock()
	cache, cached := passwordResetUpsertCache[key]
	passwordResetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			passwordResetColumns,
			passwordResetColumnsWithDefault,
			passwordResetColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			passwordResetColumns,
			passwordResetPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert password_resets, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "password_resets", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `password_resets` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(passwordResetType, passwordResetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(passwordResetType, passwordResetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for password_resets")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == passwordResetMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(passwordResetType, passwordResetMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for password_resets")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for password_resets")
	}

CacheNoHooks:
	if !cached {
		passwordResetUpsertCacheMut.Lock()
		passwordResetUpsertCache[key] = cache
		passwordResetUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PasswordReset record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PasswordReset) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PasswordReset provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), passwordResetPrimaryKeyMapping)
	sql := "DELETE FROM `password_resets` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from password_resets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for password_resets")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q passwordResetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no passwordResetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from password_resets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for password_resets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PasswordResetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PasswordReset slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(passwordResetBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordResetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `password_resets` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, passwordResetPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from passwordReset slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for password_resets")
	}

	if len(passwordResetAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PasswordReset) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPasswordReset(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PasswordResetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PasswordResetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordResetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `password_resets`.* FROM `password_resets` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, passwordResetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PasswordResetSlice")
	}

	*o = slice

	return nil
}

// PasswordResetExists checks if the PasswordReset row exists.
func PasswordResetExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `password_resets` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if password_resets exists")
	}

	return exists, nil
}
